name: lime
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # flutter 屏幕适配方案
  flutter_screenutil: ^5.5.3+2
  # Font Awesome 图标包可作为 Flutter Icons 使用
  font_awesome_flutter: ^10.1.0
  # 读取和写入简单键值对
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.7
  fl_chart: ^0.55.0
  flutter_svg: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/logo/
    - assets/svgs/
    - assets/videos/
    
  uses-material-design: true